#!/bin/bash
# Source .venv, useful with uv and other tools with this default path

source_venv() {
    if [ -d ".venv" ]; then
        source ".venv/bin/activate"
    else
        echo "No .venv directory found."
    fi
}

source_venv
